project:
  type: website
  output-dir: docs

website:
  title: "tyler-busby-portfolio"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: about.qmd
        text: "About Me"
      - href: project-portfolio.qmd
        text: "Example Project"

format:
  html:
    theme: morph
    css: styles.css
    toc: true

editor: visual

