project:
  type: website

website:
  title: "tyler-busby-portfolio"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: about.qmd
        text: "About Me"

format:
  html:
    theme: morph
    css: styles.css
    toc: true

editor: visual

